import "./globals.css";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { ReactQueryProvider } from "./ReactQueryProvider";
import { Toaster } from "react-hot-toast";

const roboto = Roboto({ weight: "300", subsets: ["cyrillic"] });

export const metadata: Metadata = {
  title: "Survey Microservice",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <ReactQueryProvider>
          {" "}
          <Toaster
            position="top-center"
            gutter={12}
            containerStyle={{ margin: "8px" }}
            toastOptions={{
              success: {
                duration: 2000,
              },
              error: {
                duration: 5000,
              },
              style: {
                fontSize: "16px",
                maxWidth: "500px",
                padding: "16px 24px",
                backgroundColor: "#f3e8ff",
                color: "#3b0764",
              },
            }}
          />
          {children}
        </ReactQueryProvider>
      </body>
    </html>
  );
}
